# bitbucket-pipelines.yml - Bitbucket Pipelines configuration
# Copyright (C) 2016-2018 Kaz Nishimura
#
# Copying and distribution of this file, with or without modification, are
# permitted in any medium without royalty provided the copyright notice and
# this notice are preserved.  This file is offered as-is, without any warranty.

# See <https://confluence.atlassian.com/bitbucket/configure-bitbucket-pipelines-yml-792298910.html>
# for details.
---
definitions:
  caches:
    openj9: /root/javasharedresources
image: adoptopenjdk/maven-openjdk8-openj9
pipelines:
  default:
    - step:
        caches:
          - maven
          - openj9
        script:
          - export MAVEN_OPTS="-Xshareclasses -Xquickstart"
          - mvn -B -s etc/settings.xml test
  branches:
    production:
      - step:
          deployment: production
          caches:
            - maven
          script:
            - apt-get update --quiet=2
            - apt-get install --quiet=2 --no-install-recommends gpg gpg-agent
            - export GNUPGHOME=`mktemp -d`
            - sh etc/gpginit.sh
            - export MAVEN_OPTS="-Xquickstart"
            - mvn -B -s etc/settings.xml ${OSSRHUSERNAME+-P ossrh} -Dmaven.deploy.skip deploy
  bookmarks:
    staging:
      - step:
          deployment: staging
          caches:
            - maven
          script:
            - apt-get update --quiet=2
            - apt-get install --quiet=2 --no-install-recommends gpg gpg-agent
            - export GNUPGHOME=`mktemp -d`
            - sh etc/gpginit.sh
            - export MAVEN_OPTS="-Xquickstart"
            - mvn -B -s etc/settings.xml ${OSSRHUSERNAME+-P ossrh} -Dmaven.deploy.skip deploy
    deployment/test:
      - step:
          deployment: test
          caches:
            - maven
          script:
            - apt-get update --quiet=2
            - apt-get install --quiet=2 --no-install-recommends gpg gpg-agent
            - export GNUPGHOME=`mktemp -d`
            - sh etc/gpginit.sh
            - export MAVEN_OPTS="-Xquickstart"
            - mvn -B -s etc/settings.xml ${OSSRHUSERNAME+-P ossrh} install
