# docker-compose.yml - compose file for test containers
# Copyright (C) 2018 Kaz Nishimura
#
# Copying and distribution of this file, with or without modification, are
# permitted in any medium without royalty provided the copyright notice and
# this notice are preserved.  This file is offered as-is, without any warranty.
---
version: "2.1"
services:
  example:
    image: kazssym/wildfly:latest
    depends_on:
      - derby
    ports:
      - "${EXAMPLE_HTTP_PORT:-8080}:8080"
      - "${EXAMPLE_MANAGEMENT_PORT:-9990}:9990"
      - "${EXAMPLE_DEBUG_PORT:-8787}:8787"
    environment:
      JAVA_OPTS:
      GC_LOG:
      DEBUG:
    volumes:
      - configuration:/opt/jboss/wildfly/standalone/configuration:rw
      - ./bitbucket-api-client-example/target/bitbucket-api-client-example-${VERSION:-5.0-SNAPSHOT}.war:/opt/jboss/wildfly/standalone/deployments/ROOT.war:ro
    working_dir: /opt/jboss/wildfly/standalone
    command: /opt/jboss/wildfly/bin/standalone.sh -b=0.0.0.0 -bmanagement=0.0.0.0
    cap_drop:
      - ALL
  derby:
    image: kazssym/derby:latest
    ports:
      - "${DERBY_PORT:-1527}:1527"
    working_dir: /opt/apache/derby/databases
    command: java -jar /opt/apache/derby/lib/derbynet.jar -h 0.0.0.0 start
    cap_drop:
      - ALL
volumes:
  configuration: {}
