# docker-compose.yml - compose file for test containers
# Copyright (C) 2018 Kaz Nishimura
#
# Copying and distribution of this file, with or without modification, are
# permitted in any medium without royalty provided the copyright notice and
# this notice are preserved.  This file is offered as-is, without any warranty.
---
version: "2.1"
services:
  liberty:
    image: open-liberty:full
    ports:
      - "${LIBERTY_HTTP_PORT:-9080}:9080"
      - "${LIBERTY_HTTPS_PORT:-9443}:9443"
    volumes:
      - ./bitbucket-webapp/target/bitbucket-webapp-${VERSION:-6-SNAPSHOT}.war:/config/dropins/webapp.war:ro
    working_dir: /config
  wildfly:
    image: kazssym/wildfly:latest
    ports:
      - "${WILDFLY_HTTP_PORT:-8080}:8080"
      - "${WILDFLY_MANAGEMENT_PORT:-9990}:9990"
      - "${WILDFLY_DEBUG_PORT:-8787}:8787"
    environment:
      DEBUG: "true"
      DEBUG_PORT: 0.0.0.0:8787
    volumes:
      - wildfly_standalone:/opt/jboss/wildfly/standalone:rw
      - ./bitbucket-webapp/target/bitbucket-webapp-${VERSION:-6-SNAPSHOT}.war:/opt/jboss/wildfly/standalone/deployments/webapp.war:ro
    working_dir: /opt/jboss/wildfly/standalone
    command: /opt/jboss/wildfly/bin/standalone.sh -b=0.0.0.0 -bmanagement=0.0.0.0
  derby:
    image: kazssym/derby:latest
    ports:
      - "${DERBY_PORT:-1527}:1527"
    working_dir: /var/tmp
    command: java -jar /opt/apache/derby/lib/derbynet.jar -h 0.0.0.0 start
volumes:
  wildfly_standalone: {}
